### ISSUE TITLE
No LICENSE file

### ISSUE THREAD

**Issue by kerrickstaley** [tomcumming/tocfl-word-list#1]
This repository doesn't have a LICENSE file specifying the license for the code/data it contains. This means I'm unable to use its code in another project. Please consider adding a license such as the Apache 2.0 license; there is an example you can copy here: https://github.com/kerrickstaley/Chinese-Prestudy/blob/master/LICENSE.md

**Comment by tomcumming** [comment]
Thanks @kerrickstaley , I am not sure how to license because I do copy some data from other sources. Have added one for now but can change again in future :+1:

**Comment by kerrickstaley** [comment]
Thanks for doing this!

I had a similar issue with multiple licenses on one of my repositories. I decided to list in my LICENSE file the specific licenses that apply to each subdirectory: https://github.com/kerrickstaley/Chinese-Vocab-List/blob/master/LICENSE.md
